### ISSUE TITLE
Propositions for .editorconfig

### ISSUE THREAD

**Issue by mcaskill** [locomotivemtl/charcoal-project-boilerplate#2]
Opening this issue after a brief discussion on Slack regarding files in the Boilerplate ignoring the current rules.

This proposition also proposes some changes to the original. I've noticed it follows, for the most part, the [example on EditorConfig](http://editorconfig.org/#example-file) which isn't tailored to Charcoal's PHP inclination.

Proposition:

```
# editorconfig.org -- For unifying the coding style between editors and IDEs

root = true

[*]
charset = utf-8
end_of_line = lf
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 4

[*.json]
insert_final_newline = false
indent_size = 2

[.{bowerrc,editorconfig,gitignore,gitattributes,htaccess,npmrc}]
insert_final_newline = false
indent_size = 2
```

**Comment by mducharme** [comment]
Yes.
Waiting for PR :+1:

**Comment by mcaskill** [comment]
Ok. I'll create a PR for each Charcoal repository (excluding Legacy) which will include the enhancements to `.editorconfig` and `.gitignore`. I'll correct as many coding standard violations as I can automate.
